// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P2_AP1_Reny20190003.DAL;

namespace P2_AP1_Reny20190003.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("P2_AP1_Reny20190003.Entidades.TiposTareas", b =>
                {
                    b.Property<int>("TipoTareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoTareaId");

                    b.ToTable("TiposTareas");

                    b.HasData(
                        new
                        {
                            TipoTareaId = 1,
                            Descripcion = "Análisis",
                            Tiempo = 0
                        },
                        new
                        {
                            TipoTareaId = 2,
                            Descripcion = "Diseño",
                            Tiempo = 0
                        },
                        new
                        {
                            TipoTareaId = 3,
                            Descripcion = "Programación",
                            Tiempo = 0
                        },
                        new
                        {
                            TipoTareaId = 4,
                            Descripcion = "Prueba",
                            Tiempo = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
